baseurl: /
languageCode: en-us
defaultContentLanguage: en
title: Okkur - Syna
theme: syna
enableGitInfo: yes
version: 0.17.4
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
ignorefiles: content/dev/.*
googleAnalytics: ''
outputs:
  home:
    - HTML
    - JSON
frontmatter:
  date:
    - date
    - lastmod
  lastmod:
    - lastmod
    - :git
    - date
markup:
  goldmark:
    renderer:
      unsafe: yes
params:
  analytics:
    piwik: {}
  colors:
    danger: '#e98300'
    dark: '#231f20'
    info: '#4298b5'
    light: '#f8f9fa'
    primary: '#00b140'
    secondary: '#75787b'
    success: '#620059'
    warning: '#fedd5c'
  custom:
    favicon: favicon.ico
    favicon_ico_sizes: 16x16 32x32
    favicon_png: favicon.png
    favicon_svg: favicon.svg
  debug: yes
  description: Open Source Theme for your next project
  fontawesome:
    disabled: no
    pro: no
  name: Okkur Labs
  style: {}
  unsafeEvents: yes
menu:
  copyright_footer:
    - name: About Us
      url: /about
      weight: 10
  footer:
    - name: WiDS Global
      url: https://www.widsconference.org/
      weight: 10
    - name: Data Science in Claremont
      url: https://datascience.library.claremont.edu/
      weight: 20
  footer_social:
    - name: github
      pre: fab fa-github fa-stack-2x
      url: https://github.com/hardin47/WiDS47_2022
      weight: 30
  main:
    - name: Home
      url: /
      weight: 10
    - name: About WiDS
      url: /content
      weight: 20
    - name: Speakers
      url: /members
      weight: 30
    - name: Registration
      url: /contact
      weight: 40
    - name: Program
      url: /fragments
      weight: 50
